### ISSUE TITLE
design mvp feed card ui and animation swipes

### ISSUE THREAD

**Issue by daviswhitehead** [daviswhitehead/shayr#22]
what does swiping left-to-right do and look like?

how far does a user need to swipe to complete the action?

what happens when the action is completed?
e.g. "Startup Episode 10 has been added to your queue"

**Comment by jessewolf** [comment]
seems like a good component for Swipe patterns
https://github.com/rishabhbhatia/react-native-swipeview

What does swiping left to right do and look like?
Feed :: Swipe Left -> Removes from feed (not for MVP), Swipe Right -> Adds post to queue (MVP)
Queue :: Swipe Left -> Removes from Queue (MVP), Swipe Right -> Marks as done and removes from queue (MVP)

![image](https://user-images.githubusercontent.com/6842437/34642878-ba6e2fd8-f2e8-11e7-9a68-d3b657d4085c.png)


How far does a user need to swipe to complete action?
The component mentioned above (SwipeView) sets the default at 35% which seems reasonable to start

What happens when the action is completed?
When the action is completed a bar with text will appear at the bottom (see mock below) with the following text:
Queue Add from Feed: "{post.Title} has been added to your queue"
Feed Remove: "{post.Title} has been removed from your feed"
Mark as done: "{post.Title} has been marked as complete"
Remove from queue: "{post.Title} has been removed from your queue" 

Note: when the # of characters in {post.Title} is > 30, cut off and use "..."

![image](https://user-images.githubusercontent.com/6842437/34642975-306a6b2e-f2ea-11e7-9047-2161e24edf0c.png)
